### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by polarstern** [QuantLet/Collaboration_Example_MVAghdis#3]
images should be updated
![mvaghdis_1-1](https://cloud.githubusercontent.com/assets/14127572/9855665/10ea8b2c-5b10-11e5-8d8d-4abe47bf3bb5.png)
![mvaghdis_2-1](https://cloud.githubusercontent.com/assets/14127572/9855666/1101bd24-5b10-11e5-900c-76c702ed356a.png)

**Comment by Tdannen** [comment]
Copied into repository
